### ISSUE TITLE
java.lang.ClassCircularityError when run phosphor

### ISSUE THREAD

**Issue by wyf18** [gmu-swe/phosphor#219]
I ran the following command on my windows laptop:

```
java -jar phosphor-driver-0.1.0.jar jdk1.8.0_111 jdk1.8.0_111-inst
```

Then I modified the environment variables `JAVA_HOME` to jdk1.8.0_111-inst, and ran `java -version`, result:
```
Error occurred during initialization of VM
java/lang/NoClassDefFoundError: edu/columbia/cs/psl/phosphor/struct/TaintedWithObjTag
```
So I gave up on instrumenting JDK, kept using jdk1.8.0_111, and ran in my project directory:
```
 java -Xbootclasspath/a:Phosphor-0.1.0.jar -javaagent:Phosphor-0.1.0.jar -cp .\target\classes\ a.b.c.WMirror
```
Then there was a long error report:

[error.txt](https://github.com/user-attachments/files/18276149/error.txt)

I don't know where went wrong, maybe I was using it in a totally wrong way?

**Comment by jon-bell** [comment]
I'm sorry - we do not have easy access to a windows 10 machine to test and debug this. However, I would welcome any pull requests that improve path handling to better support paths on windows with spaces. I have updated the README to clarify that we are aware that Phosphor does not work on Windows, and are unable to provide support for it.

**Comment by wyf18** [comment]
I reproduced this on Mac OS, and unfortunately, the error is exactly the same.

**Comment by jon-bell** [comment]
If this is an error that yo usee on Mac OS with JDK 1.8.0_111, then it is due to a configuration error when running Phosphor. However, it is not possible for me to guess what commands you have run and potential errors in those commands. I would be happy to help you get this working on Mac OS with JDK 1.8.0_111, but will need you to copy/paste (as text, not screenshots) the commands you ran and the entire output - you might find it easiest to export this to a text file and upload it as an attachment.

**Comment by wyf18** [comment]
Below is my commands
[commands.txt](https://github.com/user-attachments/files/18291820/commands.txt)
Below is my project file
[Target.zip](https://github.com/user-attachments/files/18291834/Target.zip)

I tried JDK-23 and there is no error occurred during initialization of VM, but my project specifically requires this version of JDK, so I can't change it.

**Comment by jon-bell** [comment]
I see that you have closed this issue - was that intentional (have you resolved it yourself)? The `commands.txt` file shows that you edit `.zshrc`, but not their edits or effects. I would guess that on this line: `wyf@client218-160 Target % java -Xbootclasspath/a:Phosphor-0.1.0.jar -javaagent:Phosphor-0.1.0.jar -cp .\target\classes\ a.b.c.WMirror` - you are not actually using the instrumented JVM. Please review the commands that I ran below which successfully run your example application with Phosphor:

**First: demonstrate behavior of uninstrumented application**
```
❯ mvn clean package
[INFO] Scanning for projects...
[INFO] 
[INFO] ----------------------------< a.b.c:Target >----------------------------
[INFO] Building Target 1.0-SNAPSHOT
[INFO]   from pom.xml
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- clean:3.2.0:clean (default-clean) @ Target ---
[INFO] Deleting /Users/jon/Downloads/Target/target
[INFO] 
[INFO] --- resources:3.3.1:resources (default-resources) @ Target ---
[INFO] Copying 0 resource from src/main/resources to target/classes
[INFO] 
[INFO] --- compiler:3.13.0:compile (default-compile) @ Target ---
[INFO] Recompiling the module because of changed source code.
[INFO] Compiling 4 source files with javac [debug target 8] to target/classes
[WARNING] bootstrap class path not set in conjunction with -source 8
[INFO] /Users/jon/Downloads/Target/src/main/java/a/b/c/WMirror.java: /Users/jon/Downloads/Target/src/main/java/a/b/c/WMirror.java uses unchecked or unsafe operations.
[INFO] /Users/jon/Downloads/Target/src/main/java/a/b/c/WMirror.java: Recompile with -Xlint:unchecked for details.
[INFO] 
[INFO] --- resources:3.3.1:testResources (default-testResources) @ Target ---
[INFO] skip non existing resourceDirectory /Users/jon/Downloads/Target/src/test/resources
[INFO] 
[INFO] --- compiler:3.13.0:testCompile (default-testCompile) @ Target ---
[INFO] Recompiling the module because of changed dependency.
[INFO] 
[INFO] --- surefire:3.2.5:test (default-test) @ Target ---
[INFO] 
[INFO] --- jar:3.4.1:jar (default-jar) @ Target ---
[INFO] Building jar: /Users/jon/Downloads/Target/target/Target-1.0-SNAPSHOT.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.939 s
[INFO] Finished at: 2025-01-03T09:34:35-05:00
[INFO] ------------------------------------------------------------------------
❯ java -cp target/classes a.b.c.WMirror
wm.tm is class a.b.c.TMirror
Exception in thread "main" java.lang.ClassCastException
	at java.base/java.util.concurrent.atomic.AtomicReferenceFieldUpdater$AtomicReferenceFieldUpdaterImpl.throwAccessCheckException(AtomicReferenceFieldUpdater.java:418)
	at java.base/java.util.concurrent.atomic.AtomicReferenceFieldUpdater$AtomicReferenceFieldUpdaterImpl.accessCheck(AtomicReferenceFieldUpdater.java:409)
	at java.base/java.util.concurrent.atomic.AtomicReferenceFieldUpdater$AtomicReferenceFieldUpdaterImpl.set(AtomicReferenceFieldUpdater.java:453)
	at a.b.c.WMirror.main(WMirror.java:31)
```

Create Phosphor JVM:
```
❯ java -jar phosphor-driver-0.1.0.jar /Library/Java/JavaVirtualMachines/zulu-8.jdk/Contents/Home/jre/ zulu-8-inst       
Instrumenting /Library/Java/JavaVirtualMachines/zulu-8.jdk/Contents/Home/jre to zulu-8-inst
Processed: 1000
Processed: 2000
Processed: 3000
Processed: 4000
Processed: 5000
Processed: 6000
Processed: 7000
Processed: 8000
Processed: 9000
Processed: 10000
Processed: 11000
Processed: 12000
Processed: 13000
Processed: 14000
Processed: 15000
Processed: 16000
Processed: 17000
Processed: 18000
Processed: 19000
Processed: 20000
Processed: 21000
Processed: 22000
Processed: 23000
Processed: 24000
Finished instrumentation after 12298ms
```

Run with Phosphor:

```
❯ ./zulu-8-inst/bin/java -Xbootclasspath/a:Phosphor-0.1.0.jar -javaagent:Phosphor-0.1.0.jar -cp target/classes a.b.c.WMirror
wm.tm is class a.b.c.TMirror
Exception in thread "main" java.lang.ClassCastException
	at java.util.concurrent.atomic.AtomicReferenceFieldUpdater$AtomicReferenceFieldUpdaterImpl.throwAccessCheckException(AtomicReferenceFieldUpdater.java:412)
	at java.util.concurrent.atomic.AtomicReferenceFieldUpdater$AtomicReferenceFieldUpdaterImpl.accessCheck(AtomicReferenceFieldUpdater.java:403)
	at java.util.concurrent.atomic.AtomicReferenceFieldUpdater$AtomicReferenceFieldUpdaterImpl.set(AtomicReferenceFieldUpdater.java:447)
	at a.b.c.WMirror.main(WMirror.java:31)
	at a.b.c.WMirror.main(WMirror.java)
```

**Comment by wyf18** [comment]
My issue wasn't resolved, and it  was closed by you. I'm using the Oracle JDK, downloaded from [Oracle's Java SE 8 archive page](https://www.oracle.com/java/technologies/javase/javase8-archive-downloads.html#license-lightbox). It's possible that the versions we are using are different.

I tried the following commands:

```
java -jar phosphor-driver-0.1.0.jar /Library/Java/JavaVirtualMachines/jdk1.8.0_111.jdk/Contents/Home/jre/ jdk8-inst
```
And:
```
./jdk8-inst/bin/java -Xbootclasspath/a:Phosphor-0.1.0.jar -javaagent:Phosphor-0.1.0.jar -cp target/classes a.b.c.WMirror
```
I found that when instrumenting the JVM, using the directory `/Library/Java/JavaVirtualMachines/jdk1.8.0_111.jdk` and `/Library/Java/JavaVirtualMachines/jdk1.8.0_111.jdk/Contents/Home/jre/` gave completely different results.

Final Outputs
```
./jdk8-inst/bin/java -version
Error occurred during initialization of VM
java/lang/NoClassDefFoundError: edu/columbia/cs/psl/phosphor/struct/TaintedWithObjTag
./jdk8-inst/bin/java -Xbootclasspath/a:Phosphor-0.1.0.jar -version
java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)
```
Is this correct? Does the instrumented Java require -Xbootclasspath/a:Phosphor-0.1.0.jar to run?
```
./jdk8-inst/bin/java -Xbootclasspath/a:Phosphor-0.1.0.jar -javaagent:Phosphor-0.1.0.jar -cp target/classes a.b.c.WMirror
objc[31506]: Class JavaLaunchHelper is implemented in both /Users/wyf/IdeaProjects/Target/jdk8-inst/bin/java (0x10470b4c0) and /Users/wyf/IdeaProjects/Target/jdk8-inst/lib/libinstrument.dylib (0x10d2634e0). One of the two will be used. Which one is undefined.
wm.tm is class a.b.c.TMirror
wm.tm class a.b.c.Target
toto: 3444
```
Does this output mean that Phosphor has successfully run? Shouldn't it output an analysis report (or is this program correct so there is no result)?
Thank you for your help and quick response!

**Comment by jon-bell** [comment]
> My issue wasn't resolved, and it was closed by you.

Whoops, sorry for hitting the wrong button!

>  I'm using the Oracle JDK, downloaded from [Oracle's Java SE 8 archive page](https://www.oracle.com/java/technologies/javase/javase8-archive-downloads.html#license-lightbox). It's possible that the versions we are using are different.

They are, but they both seem to work correctly. Also with the Oracle JDK, I get the same ClassCastException - perhaps the code you are running is slightly different from what you posted earlier? I get the same output that you get (no ClassCastException) if I change line 31 to `        updater.set(w, newTarget);`

> I found that when instrumenting the JVM, using the directory /Library/Java/JavaVirtualMachines/jdk1.8.0_111.jdk and /Library/Java/JavaVirtualMachines/jdk1.8.0_111.jdk/Contents/Home/jre/ gave completely different results.

Yes - the scripts expect to be passed a directory that has the contents "bin/java" etc. in it

> Final Outputs

> ./jdk8-inst/bin/java -version
> Error occurred during initialization of VM
> java/lang/NoClassDefFoundError: edu/columbia/cs/psl/phosphor/struct/TaintedWithObjTag
> ./jdk8-inst/bin/java -Xbootclasspath/a:Phosphor-0.1.0.jar -version
> java version "1.8.0_111"
> Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
> Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)
> Is this correct? Does the instrumented Java require -Xbootclasspath/a:Phosphor-0.1.0.jar to run?

Yes, this is correct. It contains the Phosphor runtime.

> ./jdk8-inst/bin/java -Xbootclasspath/a:Phosphor-0.1.0.jar -javaagent:Phosphor-0.1.0.jar -cp target/classes a.b.c.WMirror
> objc[31506]: Class JavaLaunchHelper is implemented in both /Users/wyf/IdeaProjects/Target/jdk8-inst/bin/java ?(0x10470b4c0) and /Users/wyf/IdeaProjects/Target/jdk8-inst/lib/libinstrument.dylib (0x10d2634e0). One of the two will be used. Which one is undefined.
> wm.tm is class a.b.c.TMirror
> wm.tm class a.b.c.Target
> toto: 3444
> Does this output mean that Phosphor has successfully run? Shouldn't it output an analysis report (or is this program correct so there is no result)?
> Thank you for your help and quick response!

Yup, this is the expected output - you haven't asked it to propagate any tags, or to check them. If you want Phosphor to automatically apply taint tags to the return value of a source method and check for taint tags at the start of a sink, you'll need to configure it to do so, telling it what your source(s) and sink(s) are. You can find an example of these configuration files in the [integration tests](https://github.com/gmu-swe/phosphor/tree/e38e7d6792ce92db2b99c2d6e0e1056e97abf787/integration-tests/src/test/resources).

For example, you could create the file `sources` with contents:
```
a/b/c/Target.getPassword()I
```

and the file `sinks` with contents:
```
a/b/c/TMirror.mySink(I)V
```

Then, you would configure the Phosphor java agent to use these sources and sinks and get some output:

```
❯ ./jdk8-inst/bin/java -Xbootclasspath/a:Phosphor-0.1.0.jar -javaagent:Phosphor-0.1.0.jar=taintSources=sources,taintSinks=sinks -cp target/classes a.b.c.WMirror
wm.tm is class a.b.c.TMirror
wm.tm class a.b.c.TMirror
Exception in thread "main" edu.columbia.cs.psl.phosphor.runtime.TaintSinkError: Taint [Labels = [[AutoTaintLabel [source=a/b/c/Target.getPassword()I, trace=[edu.columbia.cs.psl.phosphor.runtime.TaintSourceWrapper.autoTaint(TaintSourceWrapper.java:102), a.b.c.Target.getPassword(Target.java:8), a.b.c.WMirror.main(WMirror.java:20), a.b.c.WMirror.main(WMirror.java)]]]] flowed to sink! Value: 3444
        at edu.columbia.cs.psl.phosphor.runtime.TaintSourceWrapper.taintViolation(TaintSourceWrapper.java:214)
        at edu.columbia.cs.psl.phosphor.runtime.TaintSourceWrapper.checkTaint(TaintSourceWrapper.java:167)
        at a.b.c.TMirror.mySink(TMirror.java)
        at a.b.c.WMirror.main(WMirror.java:35)
        at a.b.c.WMirror.main(WMirror.java)
```
